version:          "3"
services:
  db:
    image:        mysql:5.7
    volumes:
      - "./files/mysql_data/:/var/lib/mysql/"
    env_file:     .env
    ports:
      - "3306:3306"
    networks:
      - db-network
  redis:
    image:        redis:alpine
    volumes:
      - "./files/redis_data/:/data/"
    networks:
      - redis-network
  php:
    image:        k2levin/php-apache-laravel:latest
    volumes:
      - "./files/apache_conf/laravel.conf:/etc/apache2/sites-enabled/laravel.conf"
      - "./files/index.html:/var/www/html/index.html"
      - "./laravel/:/var/www/app/laravel/"
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    networks:
      - redis-network
      - db-network
  npm:
    image:        k2levin/npm-service:latest
    volumes:
      - "./laravel/:/var/www/app/laravel/"
networks:
  db-network:
  redis-network:
