version:          "3"
services:
  db:
    image:        mysql:5.7
    volumes:
      - "./files/mysql_data/:/var/lib/mysql/"
    env_file:     .env
    ports:
      - "3306:3306"
    networks:
      - db-network
  redis:
    image:        redis:alpine
    volumes:
      - "./files/redis_data/:/data/"
    networks:
      - redis-network
  php:
    image:        k2levin/php-laravel:latest
    volumes:
      - "./laravel/:/var/www/app/laravel/"
    depends_on:
      - db
      - redis
    networks:
      - redis-network
      - db-network
      - web-network
  web:
    image:        nginx:alpine
    volumes:
      - "./files/nginx_conf/laravel.conf:/etc/nginx/conf.d/laravel.conf"
      - "./laravel/:/var/www/app/laravel/"
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - web-network
  npm:
    image:        k2levin/npm-service:latest
    volumes:
      - "./laravel/:/var/www/app/laravel/"
networks:
  db-network:
  redis-network:
  web-network:
